name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_HOME: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip game
        run: |
          unzip -o game.zip -d game_files
          ls -la game_files

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Ren'Py + Android
        uses: Ayowel/renpy-setup-action@v2
        with:
          action: install
          dlc: rapt
          android_sdk: true
          version: latest

      - name: Build APK
        uses: Ayowel/renpy-setup-action@v2
        with:
          action: android_build
          build_type: apk
          game: game_files
          out_dir: dist

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Game-APK
          path: dist/**/*.apk
